name: Build Sanne Script Compiler

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  linux-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt update
          sudo apt install -y gcc

      - name: Build Linux Binary
        run: |
          gcc compile.c -o compile

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compile-linux
          path: compile

  windows-build:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

          install: >
            git
            mingw-w64-x86_64-gcc
            make

      - name: Clone TinyCC
        shell: msys2 {0}
        run: |
          git clone https://github.com/TinyCC/tinycc.git

      - name: Build TinyCC
        shell: msys2 {0}
        run: |
          cd tinycc

          ./configure

          make

      - name: Build compile.exe
        shell: msys2 {0}
        run: |

          gcc compile.c ^
            -Itinycc ^
            tinycc/libtcc.a ^
            -o compile.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compile-windows
          path: compile.exe
